#!/bin/bash -l
set -e

if [ -f /.dockerenv ]; then
  source ~/.bashrc
  rvm use default
  bundle config github.com $GITHUB_USER:$GITHUB_PASS
fi

export BUNDLE_WITHOUT=development:build

function run {
  declare -a tests_command=("$@")

    echo ''
    echo "=== Running \`${tests_command[*]}\`"
    if ! ${tests_command[*]}; then
      echo "=== These tests failed."
      exit 1
    fi
}

function info {
  declare -a info_command=("$@")
    echo ''
    echo "=== Running for informational purposes \`${info_command[*]}\`"
    if ! ${info_command[*]}; then
      echo "== This test has errors and/or warnings. Please review results"
        fi
}

run bundle install --quiet
run bundle exec rspec --format=documentation

if [ -f /.dockerenv ]; then
run bundle exec danger --dangerfile=jenkins/Dangerfile --verbose
fi

